name: CI

on:

  workflow_dispatch:


jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: clone
        run: |
          chmod +x /test.sh && /test.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$(date "+%Y%m%d-%H%M")"
          git push https://${GITHUB_ACTOR}:${{ secrets.PAT }}@github.com/yleko/bd.git main --force
